name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t yogihulk/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true yogihulk/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: formal-landing-365123
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-east1-c
 
      - name: Build
        run: |-
          docker build -t yogihulk/multi-client-k8s-gh:latest -t yogihulk/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t yogihulk/multi-server-k8s-pgfix-gh:latest -t yogihulk/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t yogihulk/multi-worker-k8s-gh:latest -t yogihulk/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push yogihulk/multi-client-k8s-gh:latest
          docker push yogihulk/multi-server-k8s-pgfix-gh:latest
          docker push yogihulk/multi-worker-k8s-gh:latest
 
          docker push yogihulk/multi-client-k8s-gh:${{ env.SHA }}
          docker push yogihulk/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push yogihulk/multi-worker-k8s-gh:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=yogihulk/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=yogihulk/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=yogihulk/multi-worker-k8s-gh:${{ env.SHA }}
